### PR TITLE
fahad

### PR DESCRIPTION
**Pull request by FahadTariqiDev**

### CODE REVIEW

**Comment by amal-mohammed** [comment]
Good Fahad, you only need to modify the code to be able to display account.array as a list when it has more than one element .

**Comment by amal-mohammed** [comment]
👍

**Comment by amal-mohammed** [comment]
Sorry to re-open the pull again, but one thing that I forgot to check before closing the pull request is using the props with the components.

The question asks to display Tweets component in App component using map, this can be done by defining the array of objects (account in your solution) in the App.js, and then send the needed information to the Tweet component as props.

It would be better to work with components and props in this small lab before working on larger projects.

**Comment by FahadTariqiDev** [comment]
I just uploaded updated files, thanks for your notices

**Comment by amal-mohammed** [comment]
Perfect 👍  Thank you Fahad.

**Pull request closed without merging**
