### PR TITLE
week04_day17_React_HW - PR

### PR DESCRIPTION
**Pull request by S-MW**

### CODE REVIEW

**Comment by amal-mohammed** [comment]
Good job Saad. One thing is that the question asks to display Tweets component in App component using map, this can be done by defining the array of objects (obj in your solution ) in the App.js, and then send the needed information to the Tweet component as props.

It would be better to work with components and props in this small lab before working on larger projects.

**Comment by S-MW** [comment]
> Good job Saad. One this in that the question asks to display Tweets component in App component using map, this can be done by defining the array of objects (obj in your solution ) in the App.js, and then send the needed information to the Tweet component as props.
> 
> It would be better to work with components and props in this small lab before working on larger projects.

- Thanks Miss.Amal for this note, I'll enhance my solution to reach the best output as you said.

**Comment by S-MW** [comment]
Just finished what you mentioned before, Please have a look.

**Comment by amal-mohammed** [comment]
Perfect 👍  Thank you.

You can also do the map functionality in App.js to create multiple Tweet components and send one element as a prop, this is useful in some cases such as managing states in the Tweet component.

```
  return (
    <div className="App">
        {obj.map((element, index) => {
            return <Tweets e={element} i={index}/>
        })}
    </div>
  );
```

**Pull request closed without merging**
