### PR TITLE
HW

### PR DESCRIPTION
**Pull request by ManalAlzeer**

### CODE REVIEW

**Comment by amal-mohammed** [comment]
Perfect 👍

**Comment by amal-mohammed** [comment]
Sorry to re-open the pull again, but one thing that I forgot to check before closing the pull request is using the props with the components.

The question asks to display Tweets component in App component using map, this can be done by defining the array of objects (tweets in your solution) in the App.js, and then send the needed information to the Tweet component as props.

It would be better to work with components and props in this small lab before working on larger projects.

**Comment by ManalAlzeer** [comment]
updated App.js and tweets.js as required.

**Comment by amal-mohammed** [comment]
Good job Manal 👍  Thank you.

**Pull request closed without merging**
