### PR TITLE
react Homework

### PR DESCRIPTION
**Pull request by Faisal-Alsharif**
Faisal Alsharif

### CODE REVIEW

**Comment by amal-mohammed** [comment]
Can you push your work again? it is shown as a one file rather than a folder.

**Comment by Faisal-Alsharif** [comment]
fixed the file problem

**Comment by amal-mohammed** [comment]
Good Faisal, but you've to display the Tweets component using map rather than writing the component manually 3 times.

**Comment by amal-mohammed** [comment]
Perfect 👍 
Thanks Faisal

**Pull request closed without merging**
